POST http://localhost:3000/api/create HTTP/1.1
Content-Type: application/json

{
    "userName" : "ads",
    "title" : "louvre",
    "description" : "nice paintings and stuff",
    "rating" : 5,
    "lat" : 356,
    "long" : 345
}